# Generated by Django 5.2.9 on 2025-12-09 12:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10001_remove_clientprofile_client_afm_idx_and_more"),
        ("mydata", "0002_add_vat_period_result"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vatrecord",
            name="unique_client_mark",
        ),
        migrations.RenameIndex(
            model_name="vatrecord",
            new_name="mydata_vatr_client__7786c1_idx",
            old_name="mydata_vatr_client__5c7a3f_idx",
        ),
        migrations.RenameIndex(
            model_name="vatrecord",
            new_name="mydata_vatr_client__8bb402_idx",
            old_name="mydata_vatr_client__f1f70e_idx",
        ),
        migrations.RenameIndex(
            model_name="vatrecord",
            new_name="mydata_vatr_client__0c72fc_idx",
            old_name="mydata_vatr_client__7e6e08_idx",
        ),
        migrations.RenameIndex(
            model_name="vatrecord",
            new_name="mydata_vatr_issue_d_b8fdcb_idx",
            old_name="mydata_vatr_issue_d_e2ce3c_idx",
        ),
        migrations.RenameIndex(
            model_name="vatsynclog",
            new_name="mydata_vats_client__c0761b_idx",
            old_name="mydata_vats_client__5e7a2b_idx",
        ),
        migrations.RenameIndex(
            model_name="vatsynclog",
            new_name="mydata_vats_sync_ty_d0a3f1_idx",
            old_name="mydata_vats_sync_ty_3c8b5a_idx",
        ),
        migrations.RenameIndex(
            model_name="vatsynclog",
            new_name="mydata_vats_status_ca7d47_idx",
            old_name="mydata_vats_status_8a4c2d_idx",
        ),
        migrations.AddField(
            model_name="mydatacredentials",
            name="initial_credit_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Πιστωτικό υπόλοιπο κατά την έναρξη χρήσης του συστήματος",
                max_digits=15,
                verbose_name="Αρχικό Πιστωτικό Υπόλοιπο",
            ),
        ),
        migrations.AddField(
            model_name="mydatacredentials",
            name="initial_credit_period",
            field=models.IntegerField(
                blank=True,
                help_text="Από ποια περίοδο εφαρμόζεται (μήνας ή τρίμηνο)",
                null=True,
                verbose_name="Περίοδος Αρχικού Πιστωτικού",
            ),
        ),
        migrations.AddField(
            model_name="mydatacredentials",
            name="initial_credit_period_year",
            field=models.IntegerField(
                blank=True,
                help_text="Από ποιο έτος εφαρμόζεται το αρχικό πιστωτικό",
                null=True,
                verbose_name="Έτος Αρχικού Πιστωτικού",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vatrecord",
            unique_together={("client", "mark")},
        ),
    ]
