# Generated by Django 5.2.7 on 2025-10-31 21:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0008_monthlyobligation_hourly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('PULL_TRANSMITTED', 'Λήψη Εκδοθέντων'), ('PULL_RECEIVED', 'Λήψη Ληφθέντων'), ('PUSH_INVOICE', 'Αποστολή Παραστατικού'), ('CANCEL_INVOICE', 'Ακύρωση Παραστατικού')], max_length=20, verbose_name='Τύπος Sync')),
                ('status', models.CharField(choices=[('SUCCESS', 'Επιτυχία'), ('ERROR', 'Σφάλμα'), ('PENDING', 'Σε εκκρεμότητα')], max_length=10, verbose_name='Κατάσταση')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Έναρξη')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ολοκλήρωση')),
                ('records_processed', models.IntegerField(default=0, verbose_name='Εγγραφές που επεξεργάστηκαν')),
                ('records_created', models.IntegerField(default=0, verbose_name='Νέες Εγγραφές')),
                ('records_updated', models.IntegerField(default=0, verbose_name='Ενημερωμένες Εγγραφές')),
                ('records_failed', models.IntegerField(default=0, verbose_name='Αποτυχίες')),
                ('error_message', models.TextField(blank=True, verbose_name='Μήνυμα Σφάλματος')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Λεπτομέρειες')),
            ],
            options={
                'verbose_name': 'myDATA Sync Log',
                'verbose_name_plural': 'myDATA Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Κωδικός')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα Προϊόντος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('unit', models.CharField(choices=[('piece', 'Τεμάχια'), ('m3', 'Κυβικά Μέτρα (m³)'), ('m2', 'Τετραγωνικά Μέτρα (m²)'), ('m', 'Μέτρα'), ('kg', 'Κιλά'), ('ton', 'Τόνοι'), ('liter', 'Λίτρα')], max_length=20, verbose_name='Μονάδα Μέτρησης')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Τρέχον Απόθεμα')),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Ελάχιστο Απόθεμα (Alert)')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Τιμή Αγοράς')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Τιμή Πώλησης')),
                ('vat_category', models.IntegerField(choices=[(1, 'ΦΠΑ 24%'), (2, 'ΦΠΑ 13%'), (3, 'ΦΠΑ 6%'), (4, 'ΦΠΑ 17%'), (5, 'ΦΠΑ 9%'), (6, 'ΦΠΑ 4%'), (7, 'Χωρίς ΦΠΑ')], default=1, verbose_name='Κατηγορία ΦΠΑ')),
                ('active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Προϊόν',
                'verbose_name_plural': 'Προϊόντα',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=10, verbose_name='Σειρά')),
                ('number', models.CharField(max_length=50, verbose_name='Αριθμός')),
                ('invoice_type', models.CharField(choices=[('1.1', 'Τιμολόγιο Πώλησης'), ('1.2', 'Τιμολόγιο Πώλησης / Ενδοκοινοτικές Παραδόσεις'), ('1.3', 'Τιμολόγιο Πώλησης / Παραδόσεις Τρίτων Χωρών'), ('2.1', 'Τιμολόγιο Παροχής Υπηρεσιών'), ('5.1', 'Πιστωτικό Τιμολόγιο / Συσχετιζόμενο'), ('5.2', 'Πιστωτικό Τιμολόγιο / Μη Συσχετιζόμενο')], max_length=10, verbose_name='Τύπος Παραστατικού')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Έκδοσης')),
                ('counterpart_vat', models.CharField(max_length=20, verbose_name='ΑΦΜ Αντισυμβαλλόμενου')),
                ('counterpart_name', models.CharField(max_length=200, verbose_name='Επωνυμία Αντισυμβαλλόμενου')),
                ('is_outgoing', models.BooleanField(default=True, verbose_name='Εξερχόμενο')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Σύνολο Καθαρής Αξίας')),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Σύνολο ΦΠΑ')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Σύνολο Τελικό')),
                ('mydata_mark', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='MARK myDATA')),
                ('mydata_uid', models.CharField(blank=True, max_length=100, verbose_name='UID myDATA')),
                ('mydata_sent', models.BooleanField(default=False, verbose_name='Απεσταλμένο στο myDATA')),
                ('mydata_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημ/νία Αποστολής myDATA')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterpart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.clientprofile', verbose_name='Πελάτης/Προμηθευτής')),
            ],
            options={
                'verbose_name': 'Τιμολόγιο',
                'verbose_name_plural': 'Τιμολόγια',
                'ordering': ['-issue_date', '-number'],
                'unique_together': {('series', 'number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(verbose_name='Αριθμός Γραμμής')),
                ('description', models.CharField(max_length=300, verbose_name='Περιγραφή')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Ποσότητα')),
                ('unit', models.CharField(choices=[('piece', 'Τεμάχια'), ('m3', 'Κυβικά Μέτρα (m³)'), ('m2', 'Τετραγωνικά Μέτρα (m²)'), ('m', 'Μέτρα'), ('kg', 'Κιλά'), ('ton', 'Τόνοι'), ('liter', 'Λίτρα')], max_length=20, verbose_name='Μονάδα')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Τιμή Μονάδας')),
                ('net_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Καθαρή Αξία')),
                ('vat_category', models.IntegerField(choices=[(1, 'ΦΠΑ 24%'), (2, 'ΦΠΑ 13%'), (3, 'ΦΠΑ 6%'), (4, 'ΦΠΑ 17%'), (5, 'ΦΠΑ 9%'), (6, 'ΦΠΑ 4%'), (7, 'Χωρίς ΦΠΑ')], verbose_name='Κατηγορία ΦΠΑ')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ποσό ΦΠΑ')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.invoice', verbose_name='Τιμολόγιο')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Προϊόν')),
            ],
            options={
                'verbose_name': 'Γραμμή Τιμολογίου',
                'verbose_name_plural': 'Γραμμές Τιμολογίου',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Κατηγορίας')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productcategory', verbose_name='Γονική Κατηγορία')),
            ],
            options={
                'verbose_name': 'Κατηγορία Προϊόντος',
                'verbose_name_plural': 'Κατηγορίες Προϊόντων',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory', verbose_name='Κατηγορία'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Εισαγωγή'), ('OUT', 'Εξαγωγή'), ('ADJ', 'Διόρθωση')], max_length=3, verbose_name='Τύπος Κίνησης')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Ποσότητα')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Κόστος Μονάδας')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ημερομηνία')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Δημιουργήθηκε από')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.clientprofile', verbose_name='Προμηθευτής/Πελάτης')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.invoice', verbose_name='Παραστατικό')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Προϊόν')),
            ],
            options={
                'verbose_name': 'Κίνηση Αποθήκης',
                'verbose_name_plural': 'Κινήσεις Αποθήκης',
                'ordering': ['-date'],
            },
        ),
    ]
