# Generated by Django 5.2.9 on 2025-12-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_stockmovement_counterpart"),
        ("inventory", "9999_add_performance_indexes"),
    ]

    operations = []
