export { default as Dashboard } from './Dashboard';
export { default as Login } from './Login';
export { default as Clients } from './Clients';
export { default as Obligations } from './Obligations';
export { default as Files } from './Files';
export { default as Calls } from './Calls';
export { default as Emails } from './Emails';
export { default as Reports } from './Reports';
export { default as Settings } from './Settings';
