# Generated by Django 5.2.7 on 2025-10-07 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0009_request_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Όνομα Ομάδας')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
            ],
            options={
                'verbose_name': 'Ομάδα Υποχρεώσεων',
                'verbose_name_plural': 'Ομάδες Υποχρεώσεων',
            },
        ),
        migrations.CreateModel(
            name='ObligationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Όνομα Profile')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
            ],
            options={
                'verbose_name': 'Profile Υποχρεώσεων',
                'verbose_name_plural': 'Profiles Υποχρεώσεων',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afm', models.CharField(max_length=20, unique=True, verbose_name='Α.Φ.Μ.')),
                ('doy', models.CharField(blank=True, max_length=100, verbose_name='Δ.Ο.Υ.')),
                ('eponimia', models.CharField(max_length=200, verbose_name='Επωνυμία/Επώνυμο')),
                ('onoma', models.CharField(blank=True, max_length=100, verbose_name='Όνομα')),
                ('onoma_patros', models.CharField(blank=True, max_length=100, verbose_name='Όνομα Πατρός')),
                ('arithmos_taftotitas', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Ταυτότητας')),
                ('eidos_taftotitas', models.CharField(blank=True, max_length=50, verbose_name='Είδος Ταυτότητας')),
                ('prosopikos_arithmos', models.CharField(blank=True, max_length=50, verbose_name='Προσωπικός Αριθμός')),
                ('amka', models.CharField(blank=True, max_length=20, verbose_name='Α.Μ.Κ.Α.')),
                ('am_ika', models.CharField(blank=True, max_length=50, verbose_name='Α.Μ. Ι.Κ.Α.')),
                ('arithmos_gemi', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Γ.Ε.ΜΗ.')),
                ('arithmos_dypa', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Δ.ΥΠ.Α')),
                ('imerominia_gennisis', models.DateField(blank=True, null=True, verbose_name='Ημ. Γέννησης')),
                ('imerominia_gamou', models.DateField(blank=True, null=True, verbose_name='Ημ. Γάμου')),
                ('filo', models.CharField(blank=True, choices=[('M', 'Άνδρας'), ('F', 'Γυναίκα')], max_length=10, verbose_name='Φύλο')),
                ('diefthinsi_katoikias', models.CharField(blank=True, max_length=200, verbose_name='Διεύθυνση Κατοικίας')),
                ('arithmos_katoikias', models.CharField(blank=True, max_length=20, verbose_name='Αριθμός')),
                ('poli_katoikias', models.CharField(blank=True, max_length=100, verbose_name='Πόλη Κατοικίας')),
                ('dimos_katoikias', models.CharField(blank=True, max_length=100, verbose_name='Δήμος Κατοικίας')),
                ('nomos_katoikias', models.CharField(blank=True, max_length=100, verbose_name='Νομός Κατοικίας')),
                ('tk_katoikias', models.CharField(blank=True, max_length=10, verbose_name='T.K. Κατοικίας')),
                ('tilefono_oikias_1', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Οικίας 1')),
                ('tilefono_oikias_2', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Οικίας 2')),
                ('kinito_tilefono', models.CharField(blank=True, max_length=20, verbose_name='Κινητό τηλέφωνο')),
                ('diefthinsi_epixeirisis', models.CharField(blank=True, max_length=200, verbose_name='Διεύθυνση Επιχείρησης')),
                ('arithmos_epixeirisis', models.CharField(blank=True, max_length=20, verbose_name='Αριθμός Επιχείρησης')),
                ('poli_epixeirisis', models.CharField(blank=True, max_length=100, verbose_name='Πόλη Επιχείρησης')),
                ('dimos_epixeirisis', models.CharField(blank=True, max_length=100, verbose_name='Δήμος Επιχείρησης')),
                ('nomos_epixeirisis', models.CharField(blank=True, max_length=100, verbose_name='Νομός Επιχείρησης')),
                ('tk_epixeirisis', models.CharField(blank=True, max_length=10, verbose_name='Τ.Κ. Επιχείρησης')),
                ('tilefono_epixeirisis_1', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Επιχείρησης 1')),
                ('tilefono_epixeirisis_2', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Επιχείρησης 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('trapeza', models.CharField(blank=True, max_length=100, verbose_name='Τράπεζα')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('eidos_ipoxreou', models.CharField(choices=[('individual', 'Ιδιώτης'), ('professional', 'Επαγγελματίας'), ('company', 'Εταιρεία')], max_length=20, verbose_name='Είδος Υπόχρεου')),
                ('katigoria_vivlion', models.CharField(blank=True, choices=[('A', 'Α Κατηγορία'), ('B', 'Β Κατηγορία'), ('C', 'Γ Κατηγορία'), ('none', 'Χωρίς Βιβλία')], max_length=10, verbose_name='Κατηγορία Βιβλίων')),
                ('nomiki_morfi', models.CharField(blank=True, max_length=100, verbose_name='Νομική Μορφή')),
                ('agrotis', models.BooleanField(default=False, verbose_name='Αγρότης')),
                ('imerominia_enarksis', models.DateField(blank=True, null=True, verbose_name='Ημ/νία Έναρξης Εργασιών')),
                ('onoma_xristi_taxisnet', models.CharField(blank=True, max_length=100, verbose_name='Όνομα Χρήστη Taxis Net')),
                ('kodikos_taxisnet', models.CharField(blank=True, max_length=100, verbose_name='Κωδικός Taxis Net')),
                ('onoma_xristi_ika_ergodoti', models.CharField(blank=True, max_length=100, verbose_name='Όνομα Χρήστη Ι.Κ.Α. Εργοδότη')),
                ('kodikos_ika_ergodoti', models.CharField(blank=True, max_length=100, verbose_name='Κωδικός Ι.Κ.Α. Εργοδότη')),
                ('onoma_xristi_gemi', models.CharField(blank=True, max_length=100, verbose_name='Όνομα Χρήστη Γ.Ε.ΜΗ.')),
                ('kodikos_gemi', models.CharField(blank=True, max_length=100, verbose_name='Κωδικός Γ.Ε.ΜΗ.')),
                ('afm_sizigou', models.CharField(blank=True, max_length=20, verbose_name='Α.Φ.Μ Συζύγου')),
                ('afm_foreas', models.CharField(blank=True, max_length=20, verbose_name='Α.Φ.Μ. Φορέας')),
                ('am_klidi', models.CharField(blank=True, max_length=50, verbose_name='ΑΜ ΚΛΕΙΔΙ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_profile', to='crm.company')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_profile', to='crm.contact')),
            ],
            options={
                'verbose_name': 'Προφίλ Πελάτη',
                'verbose_name_plural': 'Προφίλ Πελατών',
            },
        ),
        migrations.CreateModel(
            name='ObligationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Όνομα')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Κωδικός')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('frequency', models.CharField(choices=[('monthly', 'Μηνιαία'), ('quarterly', 'Τριμηνιαία'), ('annual', 'Ετήσια'), ('follows_vat', 'Ακολουθεί ΦΠΑ')], max_length=20, verbose_name='Συχνότητα')),
                ('deadline_type', models.CharField(choices=[('last_day', 'Τελευταία ημέρα μήνα'), ('specific_day', 'Συγκεκριμένη ημέρα'), ('last_day_prev', 'Τελευταία προηγούμενου'), ('last_day_next', 'Τελευταία επόμενου')], max_length=20, verbose_name='Τύπος Προθεσμίας')),
                ('deadline_day', models.IntegerField(blank=True, help_text='Για συγκεκριμένη ημέρα', null=True, verbose_name='Ημέρα Προθεσμίας')),
                ('applicable_months', models.CharField(blank=True, help_text='π.χ. 3,6,9,12 ή 1 για ετήσιες', max_length=50, verbose_name='Μήνες Εφαρμογής')),
                ('priority', models.IntegerField(default=0, verbose_name='Προτεραιότητα')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('exclusion_group', models.ForeignKey(blank=True, help_text='Υποχρεώσεις στην ίδια ομάδα αλληλοαποκλείονται', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.obligationgroup', verbose_name='Ομάδα Αλληλοαποκλεισμού')),
                ('profile', models.ForeignKey(blank=True, help_text='Αν ανήκει σε profile (π.χ. Μισθοδοσία)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations', to='accounting.obligationprofile', verbose_name='Profile Υποχρεώσεων')),
            ],
            options={
                'verbose_name': 'Τύπος Υποχρέωσης',
                'verbose_name_plural': 'Τύποι Υποχρεώσεων',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='accounting.clientprofile', verbose_name='Πελάτης')),
                ('obligation_profiles', models.ManyToManyField(blank=True, to='accounting.obligationprofile', verbose_name='Profiles Υποχρεώσεων')),
                ('obligation_types', models.ManyToManyField(blank=True, limit_choices_to={'profile__isnull': True}, to='accounting.obligationtype', verbose_name='Μεμονωμένες Υποχρεώσεις')),
            ],
            options={
                'verbose_name': 'Υποχρεώσεις Πελάτη',
                'verbose_name_plural': 'Υποχρεώσεις Πελατών',
            },
        ),
        migrations.CreateModel(
            name='MonthlyObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Έτος')),
                ('month', models.IntegerField(verbose_name='Μήνας')),
                ('deadline', models.DateField(verbose_name='Προθεσμία')),
                ('status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('completed', 'Ολοκληρώθηκε'), ('overdue', 'Καθυστερεί')], default='pending', max_length=20, verbose_name='Κατάσταση')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Ημ/νία Ολοκλήρωσης')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_obligations', to='accounting.clientprofile', verbose_name='Πελάτης')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ολοκληρώθηκε από')),
                ('obligation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.obligationtype', verbose_name='Τύπος Υποχρέωσης')),
            ],
            options={
                'verbose_name': 'Μηνιαία Υποχρέωση',
                'verbose_name_plural': 'Μηνιαίες Υποχρεώσεις',
                'ordering': ['deadline', 'client__eponimia'],
                'unique_together': {('client', 'obligation_type', 'year', 'month')},
            },
        ),
    ]
