# Generated by Django 5.2.7 on 2025-10-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_clientprofile_onoma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='doy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Δ.Ο.Υ.'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='onoma_patros',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα Πατρός'),
        ),
    ]
