# Generated by Django 5.2.7 on 2025-10-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_clientprofile_afm_foreas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientobligation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='clientobligation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ημ/νία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='clientobligation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ενεργό'),
        ),
        migrations.AlterField(
            model_name='clientobligation',
            name='obligation_types',
            field=models.ManyToManyField(blank=True, to='accounting.obligationtype', verbose_name='Μεμονωμένες Υποχρεώσεις'),
        ),
    ]
