# Generated by Django 5.2.7 on 2025-10-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_clientobligation_updated_at_and_more'),
    ]

    operations = [
    ]
