# Generated by Django 5.2.7 on 2025-10-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20251008_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientobligation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ημ/νία Ενημέρωσης'),
        ),
        migrations.AlterField(
            model_name='clientobligation',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_settings', to='accounting.clientprofile', verbose_name='Πελάτης'),
        ),
    ]
