# Generated by Django 5.2.7 on 2025-10-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_clientobligation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyobligation',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=8, null=True, verbose_name='Ωριαία Χρέωση (€)'),
        ),
        migrations.AddField(
            model_name='monthlyobligation',
            name='time_spent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='π.χ. 1.5 για 1 ώρα και 30 λεπτά', max_digits=5, null=True, verbose_name='Χρόνος Εργασίας (ώρες)'),
        ),
    ]
