# Generated by Django 5.2.7 on 2025-11-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_monthlyobligation_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyobligation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='obligations/%Y/%m/', verbose_name='Συνημμένο Αρχείο'),
        ),
    ]
