# Generated by Django 5.2.7 on 2025-11-01 18:56

import accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_monthlyobligation_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyobligation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyobligation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='monthlyobligation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=accounting.models.obligation_upload_path, verbose_name='Συνημμένο Αρχείο'),
        ),
    ]
