# Generated by Django 5.2.7 on 2025-11-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_monthlyobligation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyobligation',
            options={'ordering': ['deadline', 'client__eponimia'], 'verbose_name': 'Μηνιαία Υποχρέωση', 'verbose_name_plural': 'Μηνιαίες Υποχρεώσεις'},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyobligation',
            unique_together={('client', 'obligation_type', 'year', 'month')},
        ),
    ]
