# Generated by Django 5.2.7 on 2025-11-02 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_monthlyobligation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoIPCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=50, unique=True, verbose_name='ID Κλήσης (CallMonitor)')),
                ('direction', models.CharField(choices=[('incoming', 'Εισερχόμενη'), ('outgoing', 'Εξερχόμενη')], max_length=20, verbose_name='Κατεύθυνση')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Αριθμός Τηλεφώνου')),
                ('status', models.CharField(choices=[('active', 'Ενεργή'), ('completed', 'Ολοκληρώθηκε'), ('missed', 'Αναπάντητη'), ('failed', 'Αποτυχία')], default='active', max_length=20, verbose_name='Κατάσταση')),
                ('started_at', models.DateTimeField(verbose_name='Ώρα Έναρξης')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ώρα Λήξης')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Διάρκεια (δευτερόλεπτα)')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('ticket_created', models.BooleanField(default=False, verbose_name='Τίκετ Δημιουργήθηκε')),
                ('ticket_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Τίκετ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Καταγραφή')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημέρωση')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voip_calls', to='accounting.clientprofile', verbose_name='Πελάτης')),
            ],
            options={
                'verbose_name': 'Κλήση VoIP',
                'verbose_name_plural': 'Κλήσεις VoIP',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['call_id'], name='accounting__call_id_0024e8_idx'), models.Index(fields=['phone_number'], name='accounting__phone_n_dbe478_idx'), models.Index(fields=['client'], name='accounting__client__75a8ab_idx')],
            },
        ),
    ]
