# Generated by Django 5.2.7 on 2025-11-02 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_voipcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoIPCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('started', 'Έναρξη'), ('ended', 'Λήξη'), ('ticket_created', 'Δημιουργία τίκετ'), ('client_matched', 'Σύνδεση με πελάτη'), ('status_changed', 'Αλλαγή κατάστασης')], max_length=50, verbose_name='Ενέργεια')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Χρονοσήμανση')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounting.voipcall', verbose_name='Κλήση')),
            ],
            options={
                'verbose_name': 'Καταγραφή Κλήσης',
                'verbose_name_plural': 'Καταγραφές Κλήσεων',
                'ordering': ['-created_at'],
            },
        ),
    ]
