# Generated by Django 5.2.7 on 2025-11-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_voipcalllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='voipcall',
            name='client_email',
            field=models.EmailField(blank=True, help_text='Email που αυτόματα συμπληρώθηκε', max_length=254, null=True, verbose_name='Email Πελάτη'),
        ),
    ]
