# Generated by Django 5.2.7 on 2025-11-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_voipcall_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='voipcalllog',
            name='resolution',
            field=models.CharField(blank=True, choices=[('pending', '⏳ Εκρεμμότητα'), ('closed', '✅ Κλειστή'), ('follow_up', '📞 Ακολουθήστε')], default='pending', max_length=20, verbose_name='Ευстάθεια'),
        ),
    ]
