# Generated by Django 5.2.7 on 2025-11-02 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_voipcalllog_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα Προτύπου')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('subject', models.CharField(max_length=500, verbose_name='Θέμα Email')),
                ('body_html', models.TextField(verbose_name='Κείμενο (HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
            ],
            options={
                'verbose_name': 'Πρότυπο Email',
                'verbose_name_plural': 'Πρότυπα Email',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='voipcalllog',
            name='resolution',
        ),
        migrations.AddField(
            model_name='voipcall',
            name='resolution',
            field=models.CharField(blank=True, choices=[('pending', '⏳ Εκρεμμότητα'), ('closed', '✅ Κλειστή'), ('follow_up', '📞 Follow-up')], default='pending', max_length=20, verbose_name='Ευστάθεια'),
        ),
        migrations.AlterField(
            model_name='voipcall',
            name='call_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID Κλήσης'),
        ),
        migrations.AlterField(
            model_name='voipcall',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Πελάτη'),
        ),
        migrations.CreateModel(
            name='EmailAutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα Κανόνα')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('trigger', models.CharField(choices=[('on_complete', 'Όταν ολοκληρώνεται υποχρέωση'), ('before_deadline', 'Πριν την προθεσμία'), ('on_overdue', 'Όταν καθυστερεί'), ('manual', 'Χειροκίνητα')], max_length=50, verbose_name='Trigger')),
                ('timing', models.CharField(choices=[('immediate', '⚡ Άμεσα'), ('delay_1h', '⏰ Μετά από 1 ώρα'), ('delay_24h', '📅 Επόμενη ημέρα'), ('scheduled', '🕐 Συγκεκριμένη ώρα')], default='immediate', max_length=50, verbose_name='Χρονοδιάγραμμα')),
                ('scheduled_time', models.TimeField(blank=True, help_text='Για timing "Συγκεκριμένη ώρα"', null=True, verbose_name='Ώρα Αποστολής')),
                ('days_before_deadline', models.IntegerField(blank=True, null=True, verbose_name='Ημέρες πριν την προθεσμία')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filter_obligation_types', models.ManyToManyField(blank=True, help_text='Αν άδειο, ισχύει για όλους τους τύπους', to='accounting.obligationtype', verbose_name='Φίλτρο Τύπων Υποχρέωσης')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.emailtemplate', verbose_name='Πρότυπο Email')),
            ],
            options={
                'verbose_name': 'Κανόνας Αυτοματοποίησης',
                'verbose_name_plural': 'Κανόνες Αυτοματοποίησης',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email Παραλήπτη')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Όνομα Παραλήπτη')),
                ('subject', models.CharField(max_length=500, verbose_name='Θέμα')),
                ('body_html', models.TextField(verbose_name='Κείμενο')),
                ('send_at', models.DateTimeField(db_index=True, verbose_name='Αποστολή στις')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Στάλθηκε στις')),
                ('status', models.CharField(choices=[('pending', '⏳ Εκκρεμεί'), ('sent', '✅ Στάλθηκε'), ('failed', '❌ Απέτυχε'), ('cancelled', '🚫 Ακυρώθηκε')], default='pending', max_length=20, verbose_name='Κατάσταση')),
                ('error_message', models.TextField(blank=True, verbose_name='Μήνυμα Σφάλματος')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.emailautomationrule', verbose_name='Κανόνας Αυτοματοποίησης')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.clientprofile', verbose_name='Πελάτης')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_emails', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('obligations', models.ManyToManyField(help_text='Οι υποχρεώσεις που αφορά το email', to='accounting.monthlyobligation', verbose_name='Υποχρεώσεις')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.emailtemplate', verbose_name='Πρότυπο')),
            ],
            options={
                'verbose_name': 'Προγραμματισμένο Email',
                'verbose_name_plural': 'Προγραμματισμένα Email',
                'ordering': ['send_at'],
            },
        ),
    ]
