# Generated by Django 5.2.7 on 2025-11-02 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_emailtemplate_remove_voipcalllog_resolution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Αυτόματα συμπληρώνεται', max_length=200, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, help_text='Λεπτομέρειες για τη κλήση', verbose_name='Περιγραφή')),
                ('status', models.CharField(choices=[('open', '🔴 Ανοιχτό'), ('assigned', '👤 Ανατεθειμένο'), ('in_progress', '⏳ Σε εξέλιξη'), ('resolved', '✅ Επιλυμένο'), ('closed', '🔒 Κλειστό')], default='open', max_length=20, verbose_name='Κατάσταση')),
                ('priority', models.CharField(choices=[('low', '🟢 Χαμηλή'), ('medium', '🟡 Μέση'), ('high', '🔴 Υψηλή'), ('urgent', '🚨 Επείγουσα')], default='high', max_length=20, verbose_name='Προτεραιότητα')),
                ('notes', models.TextField(blank=True, help_text='Εσωτερικές σημειώσεις', verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Ανατέθηκε')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Επιλύθηκε')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Κλειστό')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email στάλθηκε')),
                ('follow_up_scheduled', models.BooleanField(default=False, verbose_name='Follow-up Προγραμματισμένο')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Ανατεθειμένο σε')),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='accounting.voipcall', verbose_name='Κλήση')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voip_tickets', to='accounting.clientprofile', verbose_name='Πελάτης')),
            ],
            options={
                'verbose_name': 'Ticket (Missed Call)',
                'verbose_name_plural': 'Tickets (Missed Calls)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='accounting__status_613787_idx'), models.Index(fields=['client', 'status'], name='accounting__client__f6d08b_idx'), models.Index(fields=['assigned_to', 'status'], name='accounting__assigne_ccd1ab_idx'), models.Index(fields=['-created_at'], name='accounting__created_e77078_idx')],
            },
        ),
    ]
