# Generated by Django 5.2.7 on 2025-11-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_clientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='document_category',
            field=models.CharField(choices=[('contracts', '📜 Συμβάσεις'), ('invoices', '🧾 Τιμολόγια'), ('tax', '📋 Φορολογικά'), ('myf', '📊 ΜΥΦ'), ('vat', '💶 ΦΠΑ'), ('payroll', '👥 Μισθοδοσία'), ('general', '📁 Γενικά')], default='general', max_length=20),
        ),
    ]
