# Generated by Django 5.2.7 on 2025-11-08 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_clientdocument_document_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyobligation',
            name='attachment',
        ),
        migrations.AddField(
            model_name='monthlyobligation',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='List of attachment paths for multiple files'),
        ),
        migrations.CreateModel(
            name='ArchiveConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename_pattern', models.CharField(default='{type_code}_{month}_{year}.pdf', help_text='Variables: {year}, {month}, {day}, {client_afm}, {client_name}, {type_code}', max_length=200)),
                ('folder_pattern', models.CharField(default='clients/{client_afm}_{client_name}/{year}/{month}/{type_code}/', help_text='Folder structure pattern', max_length=200)),
                ('create_subfolder', models.BooleanField(default=False)),
                ('subfolder_name', models.CharField(blank=True, max_length=100)),
                ('allow_multiple_files', models.BooleanField(default=False)),
                ('auto_rename', models.BooleanField(default=True)),
                ('keep_original_name', models.BooleanField(default=False)),
                ('obligation_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive_config', to='accounting.obligationtype')),
            ],
            options={
                'verbose_name': 'Ρύθμιση Αρχειοθέτησης',
                'verbose_name_plural': 'Ρυθμίσεις Αρχειοθέτησης',
            },
        ),
    ]
