# Generated by Django 5.2.7 on 2025-11-08 18:33

import accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_remove_monthlyobligation_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Έγγραφο Πελάτη', 'verbose_name_plural': 'Έγγραφα Πελατών'},
        ),
        migrations.AddField(
            model_name='monthlyobligation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=accounting.models.obligation_upload_path, verbose_name='Συνημμένο Αρχείο'),
        ),
    ]
