# Generated by Django 5.2.7 on 2025-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_clientdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ενεργός'),
        ),
        migrations.AlterField(
            model_name='monthlyobligation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='temp_uploads/', verbose_name='Συνημμένο Αρχείο'),
        ),
    ]
