# Generated by Django 5.2.7 on 2025-12-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_default_email_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledemail',
            name='recipient_email',
            field=models.TextField(
                help_text='Πολλαπλά emails χωρισμένα με κόμμα ή νέα γραμμή',
                verbose_name='Email Παραλήπτη/ών'
            ),
        ),
        migrations.AlterField(
            model_name='scheduledemail',
            name='recipient_name',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Πολλαπλά ονόματα χωρισμένα με κόμμα ή νέα γραμμή',
                verbose_name='Όνομα Παραλήπτη/ών'
            ),
        ),
    ]
