# Generated by Django 5.2.9 on 2025-12-16
# Manual migration to convert ObligationType.profile ForeignKey to profiles ManyToManyField

from django.db import migrations, models


def migrate_profile_to_profiles(apps, schema_editor):
    """Migrate existing profile FK relationships to M2M profiles"""
    ObligationType = apps.get_model('accounting', 'ObligationType')

    # For each type with a profile, add it to the new M2M relationship
    for otype in ObligationType.objects.filter(profile__isnull=False):
        if otype.profile:
            otype.profiles.add(otype.profile)


def reverse_profiles_to_profile(apps, schema_editor):
    """Reverse migration: take first profile from M2M and set as FK"""
    ObligationType = apps.get_model('accounting', 'ObligationType')

    for otype in ObligationType.objects.all():
        first_profile = otype.profiles.first()
        if first_profile:
            otype.profile = first_profile
            otype.save(update_fields=['profile'])


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10002_ticket_call_nullable"),
    ]

    operations = [
        # Step 1: Add the new ManyToMany field
        migrations.AddField(
            model_name='obligationtype',
            name='profiles',
            field=models.ManyToManyField(
                blank=True,
                help_text='Σε ποια profiles ανήκει (μπορεί σε πολλά)',
                related_name='obligation_types',
                to='accounting.obligationprofile',
                verbose_name='Profiles Υποχρεώσεων'
            ),
        ),
        # Step 2: Run data migration to copy FK to M2M
        migrations.RunPython(migrate_profile_to_profiles, reverse_profiles_to_profile),
        # Step 3: Remove the old ForeignKey field
        migrations.RemoveField(
            model_name='obligationtype',
            name='profile',
        ),
        # Step 4: Update ClientObligation.obligation_types to remove profile filter
        migrations.AlterField(
            model_name='clientobligation',
            name='obligation_types',
            field=models.ManyToManyField(
                blank=True,
                to='accounting.obligationtype',
                verbose_name='Μεμονωμένες Υποχρεώσεις'
            ),
        ),
    ]
