# Generated by Django 5.2.9 on 2025-12-09 12:36

import accounting.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "10000_merge_20251205_1439"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="clientprofile",
            name="client_afm_idx",
        ),
        migrations.RemoveIndex(
            model_name="clientprofile",
            name="client_active_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="clientprofile",
            name="client_company_idx",
        ),
        migrations.RemoveIndex(
            model_name="monthlyobligation",
            name="mo_status_deadline_idx",
        ),
        migrations.RemoveIndex(
            model_name="monthlyobligation",
            name="mo_client_ym_idx",
        ),
        migrations.RemoveIndex(
            model_name="monthlyobligation",
            name="mo_deadline_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="monthlyobligation",
            name="mo_deadline_desc_idx",
        ),
        migrations.RemoveIndex(
            model_name="monthlyobligation",
            name="mo_completed_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduledemail",
            name="email_status_send_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduledemail",
            name="email_client_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="ticket",
            name="ticket_status_prio_idx",
        ),
        migrations.RemoveIndex(
            model_name="ticket",
            name="ticket_assigned_idx",
        ),
        migrations.RemoveIndex(
            model_name="voipcall",
            name="voip_status_start_idx",
        ),
        migrations.RemoveIndex(
            model_name="voipcall",
            name="voip_client_start_idx",
        ),
        migrations.RenameIndex(
            model_name="emaillog",
            new_name="accounting__client__060428_idx",
            old_name="accounting__client__7d2cc2_idx",
        ),
        migrations.RenameIndex(
            model_name="emaillog",
            new_name="accounting__status_be42e1_idx",
            old_name="accounting__status_3f4dc1_idx",
        ),
        migrations.RenameIndex(
            model_name="emaillog",
            new_name="accounting__sent_at_d3472f_idx",
            old_name="accounting__sent_at_a6b9c2_idx",
        ),
        migrations.AddField(
            model_name="monthlyobligation",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_obligations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ανατεθειμένο σε",
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="eidos_ipoxreou",
            field=models.CharField(
                choices=[
                    ("individual", "Ιδιώτης"),
                    ("professional", "Επαγγελματίας"),
                    ("company", "Εταιρεία"),
                ],
                default="professional",
                max_length=20,
                verbose_name="Είδος Υπόχρεου",
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Ενεργός"
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="body_html",
            field=models.TextField(
                help_text="Υποστηρίζει μεταβλητές: {client_name}, {client_afm}, {obligation_type}, {deadline}, {completed_date}, {accountant_name}",
                verbose_name="Κείμενο (HTML)",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="subject",
            field=models.CharField(
                help_text="Υποστηρίζει μεταβλητές: {client_name}, {obligation_type}, {period_month}/{period_year}",
                max_length=500,
                verbose_name="Θέμα Email",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyobligation",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=accounting.models.obligation_upload_path,
                verbose_name="Συνημμένο Αρχείο",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyobligation",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_obligations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ολοκληρώθηκε από",
            ),
        ),
    ]
