# Generated by Django 5.2.9 on 2025-12-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0026_bulk_scheduled_email_recipients"),
        ("accounting", "9999_add_performance_indexes"),
    ]

    operations = []
